[app]
port = 8080

[cache]
enabled = true
type = "boltdb"
path = "cache.db"
durationInMinutes = 60

[renderer]
debugMode = true
container = false
headless = false
windowWidth = 1920
windowHeight = 1080
timeout = 30

