[app]
port = 8080

[cache]
enabled = true
type = "boltdb"
path = "cache.db"
durationInMinutes = 60

[renderer]
windowWidth = 1920
windowHeight = 1080
userAgent = ""
container = false
headless = false
timeout = 30


