[app]
port = 8080

[cache]
enabled = true
type = "boltdb"
path = "cache.db"
durationInMinutes = 60
cleanupIntervalInMinutes = 60

[renderer]
windowWidth = 1920
windowHeight = 1080
userAgent = ""
container = false
headless = true
timeout = 30

[queue]
capacity = 1
workers = 1

[semaphore]
capacity = 5



