AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to setup entrypoit for wrenderer

Parameters:
  WrendererDomain:
    Type: String
    Description: 'Domain planned to use on Wrenderer'

  WrendererName:
    Type: String
    Description: 'Base name for creating wrenderer resources'

  WrendererCertificateArn:
    Type: String
    Description: 'Certificate ARN for wrenderer domain'

  WrendererBucketDomain:
    Type: String
    Description: 'Domain for s3 bucket origin'

  WrendererApiDomain:
    Type: String
    Description: 'Domain for api gateway origin'

  WrendererApiStage:
    Type: String
    Description: 'Deployment stage for api gateway used in origin'

Resources:
  WrendererCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref WrendererDomain 
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
            CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'
            Compress: True
            PathPattern: '/page/*'
            TargetOriginId: '[S3] wrenderer'
            ViewerProtocolPolicy: 'redirect-to-https'
        Comment: !Sub 'wrenderer distribution with domain ${WrendererDomain}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'
          Compress: True
          OriginRequestPolicyId: 'b689b0a8-53d0-40ab-baf2-68738e2966ac'
          TargetOriginId: '[Api Gateway] wrenderer'
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: True
        HttpVersion: 'http2'
        Origins:
          - DomainName: !Ref WrendererBucketDomain
            Id: '[S3] wrenderer'
            S3OriginConfig: 
              OriginAccessIdentity: ''
          - CustomOriginConfig:
              OriginProtocolPolicy: 'https-only'
              OriginSSLProtocols:
                - 'TLSv1.2'
            DomainName: !Ref WrendererApiDomain
            Id: '[Api Gateway] wrenderer'
            OriginPath:  !Sub '/${WrendererApiStage}'
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref WrendererCertificateArn
          MinimumProtocolVersion: 'TLSv1.2_2021'
          SslSupportMethod: 'sni-only'
      Tags:
        - Key: wrenderer
          Value: !Ref WrendererName

Outputs:
  WrendererDistributionId:
    Description: 'Id of created distribution'
    Value: !Ref WrendererCloudFrontDistribution
  WrendererDistributionDomain:
    Description: 'CloudFront domain of created distribution'
    Value: !GetAtt WrendererCloudFrontDistribution.DomainName
          
              
              
            
